"""
Django settings for tokenu_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import os
import json


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-27v(m^5@&rqfjbo*zmrox%dc4r#nnp2407i@4&ia=g73skh54d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tokenu',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tokenu_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tokenu_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# PINATA_JWT = os.getenv('PINATA_JWT')
# PINATA_GATEWAY = os.getenv('PINATA_GATEWAY')

load_dotenv()  # Cargar variables del archivo .env

# Variables de Pinata
PINATA_JWT = os.getenv('PINATA_JWT')
PINATA_GATEWAY = os.getenv('PINATA_GATEWAY')
PINATA_GATEWAY_KEY = os.getenv('PINATA_GATEWAY_KEY')

# URLs de Alchemy
ETHEREUM_ALCHEMY_URL = os.getenv('ETHEREUM_ALCHEMY_URL')
POLYGON_ALCHEMY_URL = os.getenv('POLYGON_ALCHEMY_URL')

# Direcciones de contratos
ETHEREUM_CONTRACT_ADDRESS = os.getenv('ETHEREUM_CONTRACT_ADDRESS')
POLYGON_CONTRACT_ADDRESS = os.getenv('POLYGON_CONTRACT_ADDRESS')

# Credenciales de cuenta
ACCOUNT_ADDRESS = os.getenv('ACCOUNT_ADDRESS')
PRIVATE_KEY = os.getenv('PRIVATE_KEY')

POLYGON_CONTRACT_ABI_PATH = os.getenv("POLYGON_CONTRACT_ABI_PATH")
# Cargar el ABI del contrato desde el archivo JSON
with open(os.path.join(BASE_DIR, POLYGON_CONTRACT_ABI_PATH), 'r') as abi_file:
    POLYGON_CONTRACT_ABI = json.load(abi_file)

ETHEREUM_CONTRACT_ABI_PATH = os.getenv("ETHEREUM_CONTRACT_ABI_PATH")
# Cargar el ABI del contrato desde el archivo JSON
with open(os.path.join(BASE_DIR, ETHEREUM_CONTRACT_ABI_PATH), 'r') as abi_file:
    ETHEREUM_CONTRACT_ABI = json.load(abi_file)